when:
  branch: main
  event: [push, pull_request]

steps:
  maven_build:
    image: maven:3.9.11-amazoncorretto-24-al2023
    commands:
      - mvn -B -ntp clean package

  build_push_image:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      USERNAME:
        from_secret: GHCR_USERNAME
      TOKEN:
        from_secret: GHCR_TOKEN
    commands:
      - export IMAGE="ghcr.io/$${USERNAME}/microprimenumbers:latest"
      - echo "$${TOKEN}" | docker login ghcr.io -u "$${USERNAME}" --password-stdin
      - docker build -t "$IMAGE" .
      - docker push "$IMAGE"

  deploy:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/servicios/microprimenumbers:/srv/microprimenumbers
    commands:
      - ls /srv/microprimenumbers
      - cd /srv/microprimenumbers
      - docker compose pull
      - docker compose up -d
