openapi: 3.0.1
info:
  title: Herramientas de números primos
  description: Microservicio que contiene algunas herramientas para visualizar o trabajar con números primos
  version: "1.0.0"

servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /v0/polar:
    post:
      summary: Lanza una función de cálculo de las coordenadas polares de los primeros x primos.
      operationId: polarCoordenates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CribaRequest'
      responses:
        '200':
          description: Cálculos realizados con éxito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolarResponse'
        '400':
          description: Petición inválida.
        '429':
          description: Demasiadas peticiones en poco tiempo.
        '500':
          description: Error interno del servidor.
        '503':
          description: API de cálculo no disponible o petición que consume más recursos que los disponibles.
  /v0/difference:
    post:
      summary: Lanza una función de cálculo de las diferencias entre los primeros x primos.
      operationId: primeDiff
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CribaRequest'
      responses:
        '200':
          description: Cálculos realizados con éxito.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiffResponse'
        '400':
          description: Petición inválida.
        '429':
          description: Demasiadas peticiones en poco tiempo.
        '500':
          description: Error interno del servidor.
        '503':
          description: API de cálculo no disponible o petición que consume más recursos que los disponibles.

components:
  schemas:
    CribaRequest:
      type: object
      required:
        - number
      properties:
        number:
          type: number
          example: 10

    PolarResponse:
      type: array
      items:
        type: object
        required:
          - axisX
          - axisY
      properties:
        axisX:
          type: number
          example: 5
        axisY:
          type: number
          example: 7
    
    DiffResponse:
      type: object
      required:
        - primos
        - diferencias
        - mensaje
      properties:
        primos:
          type: array
          items:
            type: number
        diferencias:
          type: array
          items:
            type: number
        mensaje:
          type: string
